<?php

namespace Tests\Feature;
use App\Packeges\PdfGenerator\PdfGenerator;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\View;
use Tests\TestCase;

class PdfGeneratorTest extends TestCase
{
    public $token;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $response = ($this->post("/api/en/login-test", ["user_id" => 5])->send()->getData());
        if($response){
            $this->token = "Bearer " . $response->data->token;
        }
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_example()
    {

        $response = $this->get('/api/en/test', ["Authorization" => $this->token]);
        $response->assertStatus(200);

    }
}
